# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - confluence-be

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/main_confluence-be.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npx prisma generate
          npm run build 
          cp src/generated/prisma/query-engine-debian-openssl-3.0.x dist/generated/prisma/

      - name: Zip artifact for deployment
        run: zip -r deploy.zip node_modules package-lock.json package.json dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-cf-linux
          path: backend/deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-cf-linux

      - name: Unzip artifact for deployment and cleanup
        run: |
          unzip deploy.zip
          rm deploy.zip
          ls -a
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'confluence-be'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7A81C0A91FFD4A84884C3158DAD23E36 }}
          clean: true
