# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - confluence-be4

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/windows-deployment_confluence-be4.yml"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install, build, and test
        working-directory: ./backend
        run: |
          npm ci
          npx prisma generate
          npm run build
          cp -r src/generated/prisma/query-engine-windows.exe dist/generated/prisma
          mkdir deploy
          cp -r node_modules deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp .deployment deploy/
          cp -r dist deploy/
          cp web.config deploy/
          Get-ChildItem deploy/ -Force

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: backend-cf
          path: ./backend/deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-cf

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "confluence-be4"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2A0D72F13D254EEBB39AEE27BC138D9B }}
